"""Board bring-up diagnostics: an MDIO port, a ``clk25`` counter and a UART loopback.

A minimal SoC for a board that has never been powered with a bitstream on it. It answers
the questions a new Colorlight 5A-75B rev 8.x raises and drives nothing else:

* the two Gigabit PHYs' strapped MDIO addresses and part IDs, over a bit-bang MDIO port;
* their strapped RGMII delays, read from Realtek extension page ``0xd08``;
* whether FPGA pin ``P6`` carries a clock at all, and at what rate.

Everything is reached over ``add_jtagbone()``, so the same FT232H that programs the board
is also the debug bus: no serial console and no firmware are needed to get an answer. A
gateware-only UART loopback on J19 rounds it out, proving the console wiring before any
firmware exists; it is not a management interface and is not meant to survive bring-up.

Safety, which is most of what this file is for. On rev 8.x the FPGA's 25 MHz clock is
generated by PHY1 and ``PHYRstB`` is wired to both PHYs, so any PHY reset stops the whole
design until the board is power cycled. Therefore:

* pin ``R6`` (``PHYRstB``) is never requested, so nothing can drive it;
* the ``eth`` resources are never requested either -- their RX pins are the PHYs'
  configuration straps, and an FPGA output on a strap fights a 4.7k board resistor. Only
  MDC/MDIO are added, as an extension of their own;
* the SoC is clocked from the ECP5 internal oscillator, not from ``clk25``. A diagnostic
  clocked from the signal it is diagnosing reports silence rather than an answer.
"""

from __future__ import annotations

import argparse

from migen import ClockDomain, If, Instance, Module, Signal
from migen.genlib.cdc import MultiReg
from migen.genlib.resetsync import AsyncResetSynchronizer

from litex.build.generic_platform import IOStandard, Pins, Subsignal
from litex.soc.cores.uart import UARTPHY
from litex.soc.integration.builder import Builder
from litex.soc.integration.soc_core import SoCMini
from litex.soc.interconnect.csr import AutoCSR, CSRStatus, CSRStorage

from liteeth.phy.common import LiteEthPHYMDIO

from litex_boards.platforms import colorlight_5a_75b

#: Nominal ``OSCG`` frequency before division (Lattice ECP5 sysCONFIG usage guide).
OSC_NOMINAL_HZ = 310e6

#: ``OSCG`` divider: 31 MHz. No part of this design has a performance requirement.
OSC_DIV = 10

#: Gate length in ``sys`` cycles. A power of two so the host divides by a shift.
GATE_CYCLES = 1 << 20

#: MDC/MDIO on rev 8.x, added on their own so the ``eth`` RX straps stay unrequested.
_mdio_ios = [
    (
        "mdio",
        0,
        Subsignal("mdc", Pins("R5")),
        Subsignal("mdio", Pins("T4")),
        IOStandard("LVCMOS33"),
    ),
]


class _CRG(Module):
    """``sys`` from ``OSCG``; ``clk25`` as a measured-only domain fed by pin ``P6``.

    ``clk25`` is reset-less: it may never tick, and a reset synchroniser in a domain with
    no clock never releases. Its registers come out of configuration at their init values,
    which is all the counter needs.
    """

    def __init__(self, platform, osc_div=OSC_DIV):
        self.clock_domains.cd_sys = ClockDomain()
        self.clock_domains.cd_por = ClockDomain(reset_less=True)
        self.clock_domains.cd_clk25 = ClockDomain(reset_less=True)

        osc = Signal()
        self.specials += Instance("OSCG", p_DIV=osc_div, o_OSC=osc)

        por = Signal(16, reset=(1 << 16) - 1)
        por_done = Signal()
        self.comb += [
            self.cd_por.clk.eq(osc),
            self.cd_sys.clk.eq(osc),
            self.cd_clk25.clk.eq(platform.request("clk25")),
            por_done.eq(por == 0),
        ]
        self.sync.por += If(~por_done, por.eq(por - 1))
        self.specials += AsyncResetSynchronizer(self.cd_sys, ~por_done)


class Clk25Meter(Module, AutoCSR):
    """Counts ``clk25`` rising edges over a gate of ``gate_cycles`` ``sys`` cycles.

    The two domains are unrelated and ``clk25`` may be absent entirely, so the handshake
    is a level out (``run``) and a level back (``busy``) through ``MultiReg``, not a
    ``PulseSynchronizer``: a pulse into a stopped domain is swallowed and never
    acknowledged, whereas a level that is never taken up simply reads back as idle. The
    settle window that waits for ``busy`` to fall is bounded for the same reason, so a
    clock that stops mid-gate ends the measurement with a low count instead of hanging.

    ``alive`` is set by the first ``clk25`` edge after configuration and never cleared,
    which separates "no clock at all" from "clock present at an unexpected rate".
    """

    def __init__(self, gate_cycles=GATE_CYCLES, settle_cycles=4096):
        self.start = CSRStorage(1, description="Write to start a measurement.")
        self.done = CSRStatus(1, description="Set when count is valid and stable.")
        self.count = CSRStatus(32, description="clk25 rising edges seen during the gate.")
        self.alive = CSRStatus(1, description="Set if any clk25 edge has ever been seen.")

        # # #

        run = Signal()
        busy = Signal()
        run_25 = Signal()
        run_25_d = Signal()
        alive_25 = Signal()
        count_25 = Signal(32)

        self.specials += MultiReg(run, run_25, odomain="clk25")
        self.specials += MultiReg(run_25_d, busy)
        self.specials += MultiReg(alive_25, self.alive.status[0])

        self.sync.clk25 += [
            alive_25.eq(1),
            run_25_d.eq(run_25),
            If(run_25 & ~run_25_d, count_25.eq(0)).Elif(run_25, count_25.eq(count_25 + 1)),
        ]

        gate = Signal(max=gate_cycles)
        settle = Signal(max=settle_cycles)
        gating = Signal()
        settling = Signal()

        self.comb += run.eq(gating)
        self.sync += [
            If(
                self.start.re,
                self.done.status.eq(0),
                gate.eq(gate_cycles - 1),
                gating.eq(1),
                settling.eq(0),
            )
            .Elif(
                gating,
                gate.eq(gate - 1),
                If(
                    gate == 0,
                    gating.eq(0),
                    settling.eq(1),
                    settle.eq(settle_cycles - 1),
                ),
            )
            .Elif(
                settling,
                settle.eq(settle - 1),
                If(
                    ~busy | (settle == 0),
                    settling.eq(0),
                    self.count.status.eq(count_25),
                    self.done.status.eq(1),
                ),
            ),
        ]


class DiagnosticsSoC(SoCMini):  # pylint: disable=too-many-ancestors
    """Bit-bang MDIO, a ``clk25`` counter and a UART echo, reachable over JTAG Wishbone.

    ``sys_clk_freq`` is derived from ``osc_div`` and published as a constant alongside the
    gate length, so the host computes the ``clk25`` frequency from what was built rather
    than from a number copied into two places.

    The UART echo exists so the J19 console wiring -- TX, RX, ground, the series resistor
    and the baud rate -- can be proven before any firmware exists to print from: whatever
    is typed at ``uart_baudrate`` comes back if and only if all of it is right. It is
    gateware only, with no CPU and no CSRs, so it stands independently of the jtagbone
    bridge that carries everything else here.
    """

    def __init__(self, osc_div=OSC_DIV, gate_cycles=GATE_CYCLES, uart_baudrate=115200):
        platform = colorlight_5a_75b.Platform(revision="8.2", toolchain="trellis")
        platform.add_extension(_mdio_ios)
        sys_clk_freq = int(OSC_NOMINAL_HZ / osc_div)

        SoCMini.__init__(
            self,
            platform,
            sys_clk_freq,
            ident="Board bring-up diagnostics",
            ident_version=True,
        )
        self.submodules.crg = _CRG(platform, osc_div)
        platform.add_period_constraint(self.crg.cd_sys.clk, 1e9 / sys_clk_freq)

        self.add_jtagbone()

        self.submodules.mdio = LiteEthPHYMDIO(platform.request("mdio"))

        self.submodules.clk25 = Clk25Meter(gate_cycles)

        # J19 console wiring check; see the class docstring.
        self.submodules.uart_echo = UARTPHY(platform.request("serial"), sys_clk_freq, uart_baudrate)
        self.comb += self.uart_echo.source.connect(self.uart_echo.sink)

        self.add_constant("DIAG_OSC_DIV", osc_div)
        self.add_constant("DIAG_GATE_CYCLES", gate_cycles)
        self.add_constant("DIAG_SYS_CLK_FREQ", sys_clk_freq)
        self.add_constant("DIAG_UART_BAUDRATE", uart_baudrate)


def main():
    """Build the diagnostics bitstream; load the resulting .bit with openFPGALoader."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--build", action="store_true", help="Run yosys/nextpnr/ecppack.")
    parser.add_argument("--output-dir", default="build/diagnostics", help="Build directory.")
    parser.add_argument("--osc-div", type=int, default=OSC_DIV, help="OSCG divider (2-128).")
    args = parser.parse_args()

    soc = DiagnosticsSoC(osc_div=args.osc_div)
    builder = Builder(
        soc,
        output_dir=args.output_dir,
        csr_csv=f"{args.output_dir}/csr.csv",
        compile_software=False,
    )
    builder.build(build_name="diagnostics", run=args.build)


if __name__ == "__main__":
    main()
