"""Parsing and argv rewriting for the placer-seed sweep."""

from __future__ import annotations

import pytest

from seed_sweep import Clock, argv_option, parse_fmax, seed_argv, split_build_script, summarise

SCRIPT = """# Autogenerated by LiteX / git: --------
set -e
yosys  -l forward.rpt forward.ys
nextpnr-ecp5 --json "forward.json" --lpf "forward.lpf" --textcfg "forward.config" \
 --25k --package CABGA256 --speed 7 --timing-allow-fail --seed 1
ecppack  --bootaddr 0 --compress forward.config --svf forward.svf --bit forward.bit
"""

#: nextpnr reports before routing and again after; only the second is the real figure.
LOG = """
Info: Max frequency for clock '$glbnet$crg_clkout1': 47.57 MHz (FAIL at 54.69 MHz)
Info: Max frequency for clock '$glbnet$crg_clkout0': 70.18 MHz (PASS at 62.50 MHz)
Info: Max frequency for clock '$glbnet$crg_clkout1': 59.09 MHz (PASS at 54.69 MHz)
Info: Max frequency for clock '$glbnet$crg_clkout0': 74.93 MHz (PASS at 62.50 MHz)
"""


def test_split_finds_both_tools():
    """The sweep drives the generated script's own commands rather than its own flags."""
    cmds = split_build_script(SCRIPT)
    assert cmds["yosys"] == ["yosys", "-l", "forward.rpt", "forward.ys"]
    assert argv_option(cmds["nextpnr-ecp5"], "--json") == "forward.json"
    assert argv_option(cmds["nextpnr-ecp5"], "--package") == "CABGA256"
    assert argv_option(cmds["nextpnr-ecp5"], "--absent") is None


def test_split_rejects_a_script_missing_a_tool():
    """A truncated script must fail loudly rather than sweep zero seeds."""
    with pytest.raises(ValueError, match="nextpnr-ecp5"):
        split_build_script("set -e\nyosys forward.ys\n")


def test_seed_argv_replaces_seed_and_isolates_output():
    """Concurrent seeds must not write one another's textcfg."""
    argv = split_build_script(SCRIPT)["nextpnr-ecp5"]
    third = seed_argv(argv, 3)
    assert argv_option(third, "--seed") == "3"
    assert argv_option(third, "--textcfg") == "seed3.config"
    assert third.count("--seed") == 1 and third.count("--textcfg") == 1
    assert argv_option(third, "--lpf") == "forward.lpf"
    assert argv_option(seed_argv(argv, 4), "--textcfg") == "seed4.config"


def test_parse_fmax_takes_the_post_route_figure():
    """The pre-routing estimate often reads FAIL and is not the result."""
    assert parse_fmax(LOG) == {
        "crg_clkout1": Clock(59.09, True, 54.69),
        "crg_clkout0": Clock(74.93, True, 62.50),
    }


def test_parse_fmax_carries_the_constraint_verdict():
    """The build passes --timing-allow-fail, so the FAIL is the only signal there is."""
    log = "Info: Max frequency for clock '$glbnet$eth0_rx': 120.64 MHz (FAIL at 125.00 MHz)\n"
    assert parse_fmax(log) == {"eth0_rx": Clock(120.64, False, 125.0)}


def test_parse_fmax_empty():
    """A log with no timing section yields nothing rather than raising."""
    assert not parse_fmax("Info: nothing to report\n")


def test_summarise_reports_spread():
    """The spread is what distinguishes a real gain from placer noise."""
    assert summarise([]) == "no result"
    text = summarise([57.55, 59.09, 58.01])
    assert "min 57.55" in text and "median 58.01" in text and "spread 1.54 MHz" in text
